# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 759)
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.CentralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TabWidget = QtWidgets.QTabWidget(self.CentralWidget)
        self.TabWidget.setObjectName("TabWidget")
        self.dIdVTab = QtWidgets.QWidget()
        self.dIdVTab.setObjectName("dIdVTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dIdVTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dIdVParameterFrame = QtWidgets.QFrame(self.dIdVTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dIdVParameterFrame.sizePolicy().hasHeightForWidth())
        self.dIdVParameterFrame.setSizePolicy(sizePolicy)
        self.dIdVParameterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dIdVParameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dIdVParameterFrame.setObjectName("dIdVParameterFrame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dIdVParameterFrame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dIdVDeltaLayout = QtWidgets.QVBoxLayout()
        self.dIdVDeltaLayout.setObjectName("dIdVDeltaLayout")
        self.dIdVDeltaLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dIdVDeltaLabel.setFont(font)
        self.dIdVDeltaLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dIdVDeltaLabel.setObjectName("dIdVDeltaLabel")
        self.dIdVDeltaLayout.addWidget(self.dIdVDeltaLabel)
        self.dIdVDeltaCurr = QtWidgets.QDoubleSpinBox(self.dIdVParameterFrame)
        self.dIdVDeltaCurr.setMaximum(105000.0)
        self.dIdVDeltaCurr.setProperty("value", 1.0)
        self.dIdVDeltaCurr.setObjectName("dIdVDeltaCurr")
        self.dIdVDeltaLayout.addWidget(self.dIdVDeltaCurr)
        self.gridLayout_8.addLayout(self.dIdVDeltaLayout, 1, 2, 1, 1)
        self.dIdVDelayLayout = QtWidgets.QVBoxLayout()
        self.dIdVDelayLayout.setObjectName("dIdVDelayLayout")
        self.dIdVDelayLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dIdVDelayLabel.setFont(font)
        self.dIdVDelayLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dIdVDelayLabel.setObjectName("dIdVDelayLabel")
        self.dIdVDelayLayout.addWidget(self.dIdVDelayLabel)
        self.dIdVDelay = QtWidgets.QDoubleSpinBox(self.dIdVParameterFrame)
        self.dIdVDelay.setMinimum(1.0)
        self.dIdVDelay.setMaximum(9999990.0)
        self.dIdVDelay.setProperty("value", 2.0)
        self.dIdVDelay.setObjectName("dIdVDelay")
        self.dIdVDelayLayout.addWidget(self.dIdVDelay)
        self.gridLayout_8.addLayout(self.dIdVDelayLayout, 2, 2, 1, 1)
        self.dIdVStepSizeLayout = QtWidgets.QVBoxLayout()
        self.dIdVStepSizeLayout.setObjectName("dIdVStepSizeLayout")
        self.dIdVStepSizeLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dIdVStepSizeLabel.setFont(font)
        self.dIdVStepSizeLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dIdVStepSizeLabel.setObjectName("dIdVStepSizeLabel")
        self.dIdVStepSizeLayout.addWidget(self.dIdVStepSizeLabel)
        self.dIdVStepSize = QtWidgets.QDoubleSpinBox(self.dIdVParameterFrame)
        self.dIdVStepSize.setMaximum(105000.0)
        self.dIdVStepSize.setProperty("value", 10.0)
        self.dIdVStepSize.setObjectName("dIdVStepSize")
        self.dIdVStepSizeLayout.addWidget(self.dIdVStepSize)
        self.gridLayout_8.addLayout(self.dIdVStepSizeLayout, 0, 2, 1, 1)
        self.dIdVFilterLayout = QtWidgets.QGridLayout()
        self.dIdVFilterLayout.setObjectName("dIdVFilterLayout")
        self.dIdVFilterWindowLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        self.dIdVFilterWindowLabel.setObjectName("dIdVFilterWindowLabel")
        self.dIdVFilterLayout.addWidget(self.dIdVFilterWindowLabel, 1, 0, 1, 1)
        self.dIdVFilterCountLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        self.dIdVFilterCountLabel.setObjectName("dIdVFilterCountLabel")
        self.dIdVFilterLayout.addWidget(self.dIdVFilterCountLabel, 2, 0, 1, 1)
        self.dIdVFilterCheckbox = QtWidgets.QCheckBox(self.dIdVParameterFrame)
        self.dIdVFilterCheckbox.setObjectName("dIdVFilterCheckbox")
        self.dIdVFilterLayout.addWidget(self.dIdVFilterCheckbox, 0, 1, 1, 1)
        self.dIdVFilterWindow = QtWidgets.QDoubleSpinBox(self.dIdVParameterFrame)
        self.dIdVFilterWindow.setMaximum(10.0)
        self.dIdVFilterWindow.setObjectName("dIdVFilterWindow")
        self.dIdVFilterLayout.addWidget(self.dIdVFilterWindow, 1, 1, 1, 1)
        self.dIdVFilterCount = QtWidgets.QSpinBox(self.dIdVParameterFrame)
        self.dIdVFilterCount.setMinimum(2)
        self.dIdVFilterCount.setMaximum(300)
        self.dIdVFilterCount.setProperty("value", 10)
        self.dIdVFilterCount.setObjectName("dIdVFilterCount")
        self.dIdVFilterLayout.addWidget(self.dIdVFilterCount, 2, 1, 1, 1)
        self.dIdVFilterLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dIdVFilterLabel.setFont(font)
        self.dIdVFilterLabel.setObjectName("dIdVFilterLabel")
        self.dIdVFilterLayout.addWidget(self.dIdVFilterLabel, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.dIdVFilterLayout, 8, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.FilterLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.FilterLabel.setFont(font)
        self.FilterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel.setObjectName("FilterLabel")
        self.verticalLayout.addWidget(self.FilterLabel)
        self.gridLayout_8.addLayout(self.verticalLayout, 4, 2, 1, 1)
        self.dIdVRateLayout = QtWidgets.QVBoxLayout()
        self.dIdVRateLayout.setObjectName("dIdVRateLayout")
        self.dIdVRateLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dIdVRateLabel.setFont(font)
        self.dIdVRateLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dIdVRateLabel.setObjectName("dIdVRateLabel")
        self.dIdVRateLayout.addWidget(self.dIdVRateLabel)
        self.dIdVRate = QtWidgets.QSpinBox(self.dIdVParameterFrame)
        self.dIdVRate.setMaximum(60)
        self.dIdVRate.setProperty("value", 1)
        self.dIdVRate.setObjectName("dIdVRate")
        self.dIdVRateLayout.addWidget(self.dIdVRate)
        self.gridLayout_8.addLayout(self.dIdVRateLayout, 2, 0, 1, 1)
        self.dIdVStopCurrLayout = QtWidgets.QVBoxLayout()
        self.dIdVStopCurrLayout.setObjectName("dIdVStopCurrLayout")
        self.dIdVStopCurrLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dIdVStopCurrLabel.setFont(font)
        self.dIdVStopCurrLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dIdVStopCurrLabel.setObjectName("dIdVStopCurrLabel")
        self.dIdVStopCurrLayout.addWidget(self.dIdVStopCurrLabel)
        self.dIdVStopCurr = QtWidgets.QDoubleSpinBox(self.dIdVParameterFrame)
        self.dIdVStopCurr.setMinimum(-105000.0)
        self.dIdVStopCurr.setMaximum(105000.0)
        self.dIdVStopCurr.setProperty("value", 1000.0)
        self.dIdVStopCurr.setObjectName("dIdVStopCurr")
        self.dIdVStopCurrLayout.addWidget(self.dIdVStopCurr)
        self.gridLayout_8.addLayout(self.dIdVStopCurrLayout, 1, 0, 1, 1)
        self.dIdVStartCurrLayout = QtWidgets.QVBoxLayout()
        self.dIdVStartCurrLayout.setObjectName("dIdVStartCurrLayout")
        self.dIdVStartCurrLabel = QtWidgets.QLabel(self.dIdVParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dIdVStartCurrLabel.setFont(font)
        self.dIdVStartCurrLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dIdVStartCurrLabel.setObjectName("dIdVStartCurrLabel")
        self.dIdVStartCurrLayout.addWidget(self.dIdVStartCurrLabel)
        self.dIdVStartCurr = QtWidgets.QDoubleSpinBox(self.dIdVParameterFrame)
        self.dIdVStartCurr.setMinimum(-105000.0)
        self.dIdVStartCurr.setMaximum(105000.0)
        self.dIdVStartCurr.setProperty("value", -1000.0)
        self.dIdVStartCurr.setObjectName("dIdVStartCurr")
        self.dIdVStartCurrLayout.addWidget(self.dIdVStartCurr)
        self.gridLayout_8.addLayout(self.dIdVStartCurrLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.dIdVParameterFrame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.TabWidget.addTab(self.dIdVTab, "")
        self.DeltaTab = QtWidgets.QWidget()
        self.DeltaTab.setObjectName("DeltaTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DeltaTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DeltaParameterFrame = QtWidgets.QFrame(self.DeltaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeltaParameterFrame.sizePolicy().hasHeightForWidth())
        self.DeltaParameterFrame.setSizePolicy(sizePolicy)
        self.DeltaParameterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeltaParameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeltaParameterFrame.setObjectName("DeltaParameterFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.DeltaParameterFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DeltaHighCurrLayout = QtWidgets.QVBoxLayout()
        self.DeltaHighCurrLayout.setObjectName("DeltaHighCurrLayout")
        self.DeltaHighCurrLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DeltaHighCurrLabel.setFont(font)
        self.DeltaHighCurrLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.DeltaHighCurrLabel.setObjectName("DeltaHighCurrLabel")
        self.DeltaHighCurrLayout.addWidget(self.DeltaHighCurrLabel)
        self.DeltaHighCurr = QtWidgets.QDoubleSpinBox(self.DeltaParameterFrame)
        self.DeltaHighCurr.setMinimum(-105000.0)
        self.DeltaHighCurr.setMaximum(105000.0)
        self.DeltaHighCurr.setProperty("value", 10.0)
        self.DeltaHighCurr.setObjectName("DeltaHighCurr")
        self.DeltaHighCurrLayout.addWidget(self.DeltaHighCurr)
        self.gridLayout_4.addLayout(self.DeltaHighCurrLayout, 0, 0, 1, 1)
        self.DeltaDelayLayout = QtWidgets.QVBoxLayout()
        self.DeltaDelayLayout.setObjectName("DeltaDelayLayout")
        self.DeltaDelayLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DeltaDelayLabel.setFont(font)
        self.DeltaDelayLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.DeltaDelayLabel.setObjectName("DeltaDelayLabel")
        self.DeltaDelayLayout.addWidget(self.DeltaDelayLabel)
        self.DeltaDelay = QtWidgets.QDoubleSpinBox(self.DeltaParameterFrame)
        self.DeltaDelay.setMinimum(1.0)
        self.DeltaDelay.setMaximum(9999990.0)
        self.DeltaDelay.setProperty("value", 2.0)
        self.DeltaDelay.setObjectName("DeltaDelay")
        self.DeltaDelayLayout.addWidget(self.DeltaDelay)
        self.gridLayout_4.addLayout(self.DeltaDelayLayout, 1, 1, 1, 1)
        self.DeltaPulseCountLayout = QtWidgets.QVBoxLayout()
        self.DeltaPulseCountLayout.setObjectName("DeltaPulseCountLayout")
        self.DeltaPulseCountLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DeltaPulseCountLabel.setFont(font)
        self.DeltaPulseCountLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.DeltaPulseCountLabel.setObjectName("DeltaPulseCountLabel")
        self.DeltaPulseCountLayout.addWidget(self.DeltaPulseCountLabel)
        self.DeltaPulseCount = QtWidgets.QSpinBox(self.DeltaParameterFrame)
        self.DeltaPulseCount.setMinimum(1)
        self.DeltaPulseCount.setMaximum(65536)
        self.DeltaPulseCount.setProperty("value", 100)
        self.DeltaPulseCount.setObjectName("DeltaPulseCount")
        self.DeltaPulseCountLayout.addWidget(self.DeltaPulseCount)
        self.gridLayout_4.addLayout(self.DeltaPulseCountLayout, 0, 1, 1, 1)
        self.DeltaLowCurrLayout = QtWidgets.QVBoxLayout()
        self.DeltaLowCurrLayout.setObjectName("DeltaLowCurrLayout")
        self.DeltaLowCurrLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DeltaLowCurrLabel.setFont(font)
        self.DeltaLowCurrLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.DeltaLowCurrLabel.setObjectName("DeltaLowCurrLabel")
        self.DeltaLowCurrLayout.addWidget(self.DeltaLowCurrLabel)
        self.DeltaLowCurr = QtWidgets.QDoubleSpinBox(self.DeltaParameterFrame)
        self.DeltaLowCurr.setMinimum(-105000.0)
        self.DeltaLowCurr.setMaximum(105000.0)
        self.DeltaLowCurr.setProperty("value", 0.0)
        self.DeltaLowCurr.setObjectName("DeltaLowCurr")
        self.DeltaLowCurrLayout.addWidget(self.DeltaLowCurr)
        self.gridLayout_4.addLayout(self.DeltaLowCurrLayout, 1, 0, 1, 1)
        self.DeltaFilterLayout = QtWidgets.QGridLayout()
        self.DeltaFilterLayout.setObjectName("DeltaFilterLayout")
        self.DeltaFilterWindowLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        self.DeltaFilterWindowLabel.setObjectName("DeltaFilterWindowLabel")
        self.DeltaFilterLayout.addWidget(self.DeltaFilterWindowLabel, 1, 0, 1, 1)
        self.DeltaFilterCount = QtWidgets.QSpinBox(self.DeltaParameterFrame)
        self.DeltaFilterCount.setMinimum(2)
        self.DeltaFilterCount.setMaximum(300)
        self.DeltaFilterCount.setProperty("value", 10)
        self.DeltaFilterCount.setObjectName("DeltaFilterCount")
        self.DeltaFilterLayout.addWidget(self.DeltaFilterCount, 2, 1, 1, 1)
        self.DeltaFilterCheckbox = QtWidgets.QCheckBox(self.DeltaParameterFrame)
        self.DeltaFilterCheckbox.setObjectName("DeltaFilterCheckbox")
        self.DeltaFilterLayout.addWidget(self.DeltaFilterCheckbox, 0, 1, 1, 1)
        self.DeltaFilterCountLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        self.DeltaFilterCountLabel.setObjectName("DeltaFilterCountLabel")
        self.DeltaFilterLayout.addWidget(self.DeltaFilterCountLabel, 2, 0, 1, 1)
        self.DeltaFilterWindow = QtWidgets.QDoubleSpinBox(self.DeltaParameterFrame)
        self.DeltaFilterWindow.setMaximum(10.0)
        self.DeltaFilterWindow.setObjectName("DeltaFilterWindow")
        self.DeltaFilterLayout.addWidget(self.DeltaFilterWindow, 1, 1, 1, 1)
        self.DeltaFilterComboBox = QtWidgets.QComboBox(self.DeltaParameterFrame)
        self.DeltaFilterComboBox.setObjectName("DeltaFilterComboBox")
        self.DeltaFilterComboBox.addItem("")
        self.DeltaFilterComboBox.addItem("")
        self.DeltaFilterLayout.addWidget(self.DeltaFilterComboBox, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.DeltaFilterLayout, 4, 1, 2, 1)
        self.DeltaRateLayout = QtWidgets.QVBoxLayout()
        self.DeltaRateLayout.setObjectName("DeltaRateLayout")
        self.DeltaRateLabel = QtWidgets.QLabel(self.DeltaParameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeltaRateLabel.sizePolicy().hasHeightForWidth())
        self.DeltaRateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DeltaRateLabel.setFont(font)
        self.DeltaRateLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.DeltaRateLabel.setObjectName("DeltaRateLabel")
        self.DeltaRateLayout.addWidget(self.DeltaRateLabel)
        self.DeltaRate = QtWidgets.QSpinBox(self.DeltaParameterFrame)
        self.DeltaRate.setMaximum(60)
        self.DeltaRate.setProperty("value", 1)
        self.DeltaRate.setObjectName("DeltaRate")
        self.DeltaRateLayout.addWidget(self.DeltaRate)
        self.gridLayout_4.addLayout(self.DeltaRateLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FilterLabel_2 = QtWidgets.QLabel(self.DeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.FilterLabel_2.setFont(font)
        self.FilterLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel_2.setObjectName("FilterLabel_2")
        self.verticalLayout_2.addWidget(self.FilterLabel_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.DeltaParameterFrame, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.TabWidget.addTab(self.DeltaTab, "")
        self.FixedPulseDeltaTab = QtWidgets.QWidget()
        self.FixedPulseDeltaTab.setObjectName("FixedPulseDeltaTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.FixedPulseDeltaTab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        self.FixedPulseDeltaParameterFrame = QtWidgets.QFrame(self.FixedPulseDeltaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FixedPulseDeltaParameterFrame.sizePolicy().hasHeightForWidth())
        self.FixedPulseDeltaParameterFrame.setSizePolicy(sizePolicy)
        self.FixedPulseDeltaParameterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FixedPulseDeltaParameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FixedPulseDeltaParameterFrame.setObjectName("FixedPulseDeltaParameterFrame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.FixedPulseDeltaParameterFrame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.FixedPulseDeltaLowILayout = QtWidgets.QVBoxLayout()
        self.FixedPulseDeltaLowILayout.setObjectName("FixedPulseDeltaLowILayout")
        self.FixedPulseDeltaLowILabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaLowILabel.setFont(font)
        self.FixedPulseDeltaLowILabel.setObjectName("FixedPulseDeltaLowILabel")
        self.FixedPulseDeltaLowILayout.addWidget(self.FixedPulseDeltaLowILabel)
        self.FixedPulseDeltaLowI = QtWidgets.QDoubleSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaLowI.setMinimum(-105000.0)
        self.FixedPulseDeltaLowI.setMaximum(105000.0)
        self.FixedPulseDeltaLowI.setProperty("value", 0.0)
        self.FixedPulseDeltaLowI.setObjectName("FixedPulseDeltaLowI")
        self.FixedPulseDeltaLowILayout.addWidget(self.FixedPulseDeltaLowI)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaLowILayout, 1, 0, 1, 1)
        self.FixedPulseDeltaDelayLayout = QtWidgets.QVBoxLayout()
        self.FixedPulseDeltaDelayLayout.setObjectName("FixedPulseDeltaDelayLayout")
        self.FixedPulseDeltaDelayLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaDelayLabel.setFont(font)
        self.FixedPulseDeltaDelayLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.FixedPulseDeltaDelayLabel.setObjectName("FixedPulseDeltaDelayLabel")
        self.FixedPulseDeltaDelayLayout.addWidget(self.FixedPulseDeltaDelayLabel)
        self.FixedPulseDeltaDelay = QtWidgets.QDoubleSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaDelay.setMinimum(16.0)
        self.FixedPulseDeltaDelay.setMaximum(11966.0)
        self.FixedPulseDeltaDelay.setObjectName("FixedPulseDeltaDelay")
        self.FixedPulseDeltaDelayLayout.addWidget(self.FixedPulseDeltaDelay)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaDelayLayout, 2, 0, 1, 1)
        self.FixedPulseDeltaCycleLayout = QtWidgets.QVBoxLayout()
        self.FixedPulseDeltaCycleLayout.setObjectName("FixedPulseDeltaCycleLayout")
        self.FixedPulseDeltaCycleLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaCycleLabel.setFont(font)
        self.FixedPulseDeltaCycleLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.FixedPulseDeltaCycleLabel.setObjectName("FixedPulseDeltaCycleLabel")
        self.FixedPulseDeltaCycleLayout.addWidget(self.FixedPulseDeltaCycleLabel)
        self.FixedPulseDeltaCycle = QtWidgets.QSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaCycle.setMinimum(5)
        self.FixedPulseDeltaCycle.setMaximum(999999)
        self.FixedPulseDeltaCycle.setObjectName("FixedPulseDeltaCycle")
        self.FixedPulseDeltaCycleLayout.addWidget(self.FixedPulseDeltaCycle)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaCycleLayout, 2, 1, 1, 1)
        self.FixedPulseDeltaWidthLayout = QtWidgets.QVBoxLayout()
        self.FixedPulseDeltaWidthLayout.setObjectName("FixedPulseDeltaWidthLayout")
        self.FixedPulseDeltaWidthLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaWidthLabel.setFont(font)
        self.FixedPulseDeltaWidthLabel.setObjectName("FixedPulseDeltaWidthLabel")
        self.FixedPulseDeltaWidthLayout.addWidget(self.FixedPulseDeltaWidthLabel)
        self.FixedPulseDeltaWidth = QtWidgets.QSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaWidth.setMinimum(50)
        self.FixedPulseDeltaWidth.setMaximum(12000)
        self.FixedPulseDeltaWidth.setProperty("value", 110)
        self.FixedPulseDeltaWidth.setObjectName("FixedPulseDeltaWidth")
        self.FixedPulseDeltaWidthLayout.addWidget(self.FixedPulseDeltaWidth)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaWidthLayout, 1, 1, 1, 1)
        self.FixedPulseDeltaHighILayout = QtWidgets.QVBoxLayout()
        self.FixedPulseDeltaHighILayout.setObjectName("FixedPulseDeltaHighILayout")
        self.FixedPulseDeltaHighILabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaHighILabel.setFont(font)
        self.FixedPulseDeltaHighILabel.setObjectName("FixedPulseDeltaHighILabel")
        self.FixedPulseDeltaHighILayout.addWidget(self.FixedPulseDeltaHighILabel)
        self.FixedPulseDeltaHighI = QtWidgets.QDoubleSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaHighI.setMinimum(-105000.0)
        self.FixedPulseDeltaHighI.setMaximum(105000.0)
        self.FixedPulseDeltaHighI.setProperty("value", 10.0)
        self.FixedPulseDeltaHighI.setObjectName("FixedPulseDeltaHighI")
        self.FixedPulseDeltaHighILayout.addWidget(self.FixedPulseDeltaHighI)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaHighILayout, 0, 0, 1, 1)
        self.DutyCycleLayout = QtWidgets.QVBoxLayout()
        self.DutyCycleLayout.setObjectName("DutyCycleLayout")
        self.DutyCycleLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DutyCycleLabel.setFont(font)
        self.DutyCycleLabel.setObjectName("DutyCycleLabel")
        self.DutyCycleLayout.addWidget(self.DutyCycleLabel)
        self.DutyCycle = QtWidgets.QDoubleSpinBox(self.FixedPulseDeltaParameterFrame)
        self.DutyCycle.setEnabled(True)
        self.DutyCycle.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.DutyCycle.setReadOnly(True)
        self.DutyCycle.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DutyCycle.setMaximum(9999999.0)
        self.DutyCycle.setObjectName("DutyCycle")
        self.DutyCycleLayout.addWidget(self.DutyCycle)
        self.gridLayout_10.addLayout(self.DutyCycleLayout, 3, 1, 2, 1)
        self.FixedPulseDeltaCountLayout = QtWidgets.QVBoxLayout()
        self.FixedPulseDeltaCountLayout.setObjectName("FixedPulseDeltaCountLayout")
        self.FixedPulseDeltaCountLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaCountLabel.setFont(font)
        self.FixedPulseDeltaCountLabel.setObjectName("FixedPulseDeltaCountLabel")
        self.FixedPulseDeltaCountLayout.addWidget(self.FixedPulseDeltaCountLabel)
        self.FixedPulseDeltaCount = QtWidgets.QSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaCount.setMinimum(1)
        self.FixedPulseDeltaCount.setMaximum(65536)
        self.FixedPulseDeltaCount.setProperty("value", 100)
        self.FixedPulseDeltaCount.setObjectName("FixedPulseDeltaCount")
        self.FixedPulseDeltaCountLayout.addWidget(self.FixedPulseDeltaCount)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaCountLayout, 0, 1, 1, 1)
        self.FixedPulseDeltaFilterLayout = QtWidgets.QGridLayout()
        self.FixedPulseDeltaFilterLayout.setObjectName("FixedPulseDeltaFilterLayout")
        self.FixedPulseDeltaFilterWindow = QtWidgets.QDoubleSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaFilterWindow.setMaximum(10.0)
        self.FixedPulseDeltaFilterWindow.setObjectName("FixedPulseDeltaFilterWindow")
        self.FixedPulseDeltaFilterLayout.addWidget(self.FixedPulseDeltaFilterWindow, 1, 1, 1, 1)
        self.FixedPulseDeltaFilterWindowLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaFilterWindowLabel.setObjectName("FixedPulseDeltaFilterWindowLabel")
        self.FixedPulseDeltaFilterLayout.addWidget(self.FixedPulseDeltaFilterWindowLabel, 1, 0, 1, 1)
        self.FixedPulseDeltaFilterCountLabel = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaFilterCountLabel.setObjectName("FixedPulseDeltaFilterCountLabel")
        self.FixedPulseDeltaFilterLayout.addWidget(self.FixedPulseDeltaFilterCountLabel, 2, 0, 1, 1)
        self.FixedPulseDeltaFilterCheckbox = QtWidgets.QCheckBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaFilterCheckbox.setObjectName("FixedPulseDeltaFilterCheckbox")
        self.FixedPulseDeltaFilterLayout.addWidget(self.FixedPulseDeltaFilterCheckbox, 0, 1, 1, 1)
        self.FixedPulseDeltaFilterCount = QtWidgets.QSpinBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaFilterCount.setMinimum(2)
        self.FixedPulseDeltaFilterCount.setMaximum(300)
        self.FixedPulseDeltaFilterCount.setProperty("value", 10)
        self.FixedPulseDeltaFilterCount.setObjectName("FixedPulseDeltaFilterCount")
        self.FixedPulseDeltaFilterLayout.addWidget(self.FixedPulseDeltaFilterCount, 2, 1, 1, 1)
        self.FixedPulseDeltaComboBox = QtWidgets.QComboBox(self.FixedPulseDeltaParameterFrame)
        self.FixedPulseDeltaComboBox.setObjectName("FixedPulseDeltaComboBox")
        self.FixedPulseDeltaComboBox.addItem("")
        self.FixedPulseDeltaComboBox.addItem("")
        self.FixedPulseDeltaFilterLayout.addWidget(self.FixedPulseDeltaComboBox, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.FixedPulseDeltaFilterLayout, 6, 1, 1, 1)
        self.FixedPulseDeltaLowMeasure = QtWidgets.QCheckBox(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FixedPulseDeltaLowMeasure.setFont(font)
        self.FixedPulseDeltaLowMeasure.setChecked(True)
        self.FixedPulseDeltaLowMeasure.setObjectName("FixedPulseDeltaLowMeasure")
        self.gridLayout_10.addWidget(self.FixedPulseDeltaLowMeasure, 4, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FilterLabel_3 = QtWidgets.QLabel(self.FixedPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.FilterLabel_3.setFont(font)
        self.FilterLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel_3.setObjectName("FilterLabel_3")
        self.verticalLayout_3.addWidget(self.FilterLabel_3)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.FixedPulseDeltaParameterFrame, 0, 1, 1, 1)
        self.TabWidget.addTab(self.FixedPulseDeltaTab, "")
        self.SweepPulseDeltaTab = QtWidgets.QWidget()
        self.SweepPulseDeltaTab.setObjectName("SweepPulseDeltaTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.SweepPulseDeltaTab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.SweepPulseDeltaParameterFrame = QtWidgets.QFrame(self.SweepPulseDeltaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepPulseDeltaParameterFrame.sizePolicy().hasHeightForWidth())
        self.SweepPulseDeltaParameterFrame.setSizePolicy(sizePolicy)
        self.SweepPulseDeltaParameterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SweepPulseDeltaParameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SweepPulseDeltaParameterFrame.setObjectName("SweepPulseDeltaParameterFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.SweepPulseDeltaParameterFrame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.SweepTypeComboBox = QtWidgets.QComboBox(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepTypeComboBox.setFont(font)
        self.SweepTypeComboBox.setObjectName("SweepTypeComboBox")
        self.SweepTypeComboBox.addItem("")
        self.SweepTypeComboBox.addItem("")
        self.SweepTypeComboBox.addItem("")
        self.gridLayout_9.addWidget(self.SweepTypeComboBox, 0, 0, 1, 1)
        self.SweepPulseDeltaStartILayout = QtWidgets.QGridLayout()
        self.SweepPulseDeltaStartILayout.setObjectName("SweepPulseDeltaStartILayout")
        self.SweepPulseDeltaStartI = QtWidgets.QDoubleSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaStartI.setMinimum(-105000.0)
        self.SweepPulseDeltaStartI.setMaximum(105000.0)
        self.SweepPulseDeltaStartI.setProperty("value", 1.0)
        self.SweepPulseDeltaStartI.setObjectName("SweepPulseDeltaStartI")
        self.SweepPulseDeltaStartILayout.addWidget(self.SweepPulseDeltaStartI, 1, 0, 1, 1)
        self.SweepPulseDeltaIList = QtWidgets.QPushButton(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaIList.setObjectName("SweepPulseDeltaIList")
        self.SweepPulseDeltaStartILayout.addWidget(self.SweepPulseDeltaIList, 1, 1, 1, 1)
        self.SweepPulseDeltaStartILabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaStartILabel.setFont(font)
        self.SweepPulseDeltaStartILabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaStartILabel.setObjectName("SweepPulseDeltaStartILabel")
        self.SweepPulseDeltaStartILayout.addWidget(self.SweepPulseDeltaStartILabel, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaStartILayout, 1, 0, 1, 1)
        self.SweepPulseDeltaEndILayout = QtWidgets.QVBoxLayout()
        self.SweepPulseDeltaEndILayout.setObjectName("SweepPulseDeltaEndILayout")
        self.SweepPulseDeltaEndILabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaEndILabel.setFont(font)
        self.SweepPulseDeltaEndILabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaEndILabel.setObjectName("SweepPulseDeltaEndILabel")
        self.SweepPulseDeltaEndILayout.addWidget(self.SweepPulseDeltaEndILabel)
        self.SweepPulseDeltaEndI = QtWidgets.QDoubleSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaEndI.setMinimum(-105000.0)
        self.SweepPulseDeltaEndI.setMaximum(105000.0)
        self.SweepPulseDeltaEndI.setProperty("value", 10.0)
        self.SweepPulseDeltaEndI.setObjectName("SweepPulseDeltaEndI")
        self.SweepPulseDeltaEndILayout.addWidget(self.SweepPulseDeltaEndI)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaEndILayout, 2, 0, 1, 1)
        self.SweepPulseDeltaIStepLayout = QtWidgets.QVBoxLayout()
        self.SweepPulseDeltaIStepLayout.setObjectName("SweepPulseDeltaIStepLayout")
        self.SweepPulseDeltaIStepLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaIStepLabel.setFont(font)
        self.SweepPulseDeltaIStepLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaIStepLabel.setObjectName("SweepPulseDeltaIStepLabel")
        self.SweepPulseDeltaIStepLayout.addWidget(self.SweepPulseDeltaIStepLabel)
        self.SweepPulseDeltaIStep = QtWidgets.QDoubleSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaIStep.setDecimals(5)
        self.SweepPulseDeltaIStep.setMinimum(0.1)
        self.SweepPulseDeltaIStep.setMaximum(105000.0)
        self.SweepPulseDeltaIStep.setSingleStep(1.0)
        self.SweepPulseDeltaIStep.setObjectName("SweepPulseDeltaIStep")
        self.SweepPulseDeltaIStepLayout.addWidget(self.SweepPulseDeltaIStep)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaIStepLayout, 3, 0, 1, 1)
        self.SweepPulseDeltaPointsLayout = QtWidgets.QVBoxLayout()
        self.SweepPulseDeltaPointsLayout.setObjectName("SweepPulseDeltaPointsLayout")
        self.SweepPulseDeltaPointsLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaPointsLabel.setFont(font)
        self.SweepPulseDeltaPointsLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaPointsLabel.setObjectName("SweepPulseDeltaPointsLabel")
        self.SweepPulseDeltaPointsLayout.addWidget(self.SweepPulseDeltaPointsLabel)
        self.SweepPulseDeltaPoints = QtWidgets.QSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaPoints.setReadOnly(True)
        self.SweepPulseDeltaPoints.setMinimum(1)
        self.SweepPulseDeltaPoints.setMaximum(65536)
        self.SweepPulseDeltaPoints.setProperty("value", 10)
        self.SweepPulseDeltaPoints.setObjectName("SweepPulseDeltaPoints")
        self.SweepPulseDeltaPointsLayout.addWidget(self.SweepPulseDeltaPoints)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaPointsLayout, 1, 1, 1, 1)
        self.SweepPulseDeltaSweepsLayout = QtWidgets.QVBoxLayout()
        self.SweepPulseDeltaSweepsLayout.setObjectName("SweepPulseDeltaSweepsLayout")
        self.SweepPulseDeltaSweepsLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaSweepsLabel.setFont(font)
        self.SweepPulseDeltaSweepsLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaSweepsLabel.setObjectName("SweepPulseDeltaSweepsLabel")
        self.SweepPulseDeltaSweepsLayout.addWidget(self.SweepPulseDeltaSweepsLabel)
        self.SweepPulseDeltaSweeps = QtWidgets.QSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaSweeps.setMinimum(1)
        self.SweepPulseDeltaSweeps.setObjectName("SweepPulseDeltaSweeps")
        self.SweepPulseDeltaSweepsLayout.addWidget(self.SweepPulseDeltaSweeps)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaSweepsLayout, 2, 1, 1, 1)
        self.SweepPulseDeltaWidthLayout = QtWidgets.QVBoxLayout()
        self.SweepPulseDeltaWidthLayout.setObjectName("SweepPulseDeltaWidthLayout")
        self.SweepPulseDeltaWidthLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaWidthLabel.setFont(font)
        self.SweepPulseDeltaWidthLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaWidthLabel.setObjectName("SweepPulseDeltaWidthLabel")
        self.SweepPulseDeltaWidthLayout.addWidget(self.SweepPulseDeltaWidthLabel)
        self.SweepPulseDeltaWidth = QtWidgets.QSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaWidth.setMinimum(50)
        self.SweepPulseDeltaWidth.setMaximum(12000)
        self.SweepPulseDeltaWidth.setProperty("value", 120)
        self.SweepPulseDeltaWidth.setObjectName("SweepPulseDeltaWidth")
        self.SweepPulseDeltaWidthLayout.addWidget(self.SweepPulseDeltaWidth)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaWidthLayout, 3, 1, 1, 1)
        self.SweepPulseDeltaFilterLayout = QtWidgets.QGridLayout()
        self.SweepPulseDeltaFilterLayout.setObjectName("SweepPulseDeltaFilterLayout")
        self.SweepPulseDeltaFilterLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaFilterLabel.setFont(font)
        self.SweepPulseDeltaFilterLabel.setObjectName("SweepPulseDeltaFilterLabel")
        self.SweepPulseDeltaFilterLayout.addWidget(self.SweepPulseDeltaFilterLabel, 0, 0, 1, 1)
        self.SweepPulseDeltaFilterWindowLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaFilterWindowLabel.setObjectName("SweepPulseDeltaFilterWindowLabel")
        self.SweepPulseDeltaFilterLayout.addWidget(self.SweepPulseDeltaFilterWindowLabel, 1, 0, 1, 1)
        self.SweepPulseDeltaFilterCountLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaFilterCountLabel.setObjectName("SweepPulseDeltaFilterCountLabel")
        self.SweepPulseDeltaFilterLayout.addWidget(self.SweepPulseDeltaFilterCountLabel, 2, 0, 1, 1)
        self.SweepPulseDeltaFilterCheckbox = QtWidgets.QCheckBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaFilterCheckbox.setObjectName("SweepPulseDeltaFilterCheckbox")
        self.SweepPulseDeltaFilterLayout.addWidget(self.SweepPulseDeltaFilterCheckbox, 0, 1, 1, 1)
        self.SweepPulseDeltaFilterWindow = QtWidgets.QDoubleSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaFilterWindow.setMaximum(10.0)
        self.SweepPulseDeltaFilterWindow.setObjectName("SweepPulseDeltaFilterWindow")
        self.SweepPulseDeltaFilterLayout.addWidget(self.SweepPulseDeltaFilterWindow, 1, 1, 1, 1)
        self.SweepPulseDeltaFilterCount = QtWidgets.QSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaFilterCount.setMinimum(2)
        self.SweepPulseDeltaFilterCount.setMaximum(300)
        self.SweepPulseDeltaFilterCount.setProperty("value", 10)
        self.SweepPulseDeltaFilterCount.setObjectName("SweepPulseDeltaFilterCount")
        self.SweepPulseDeltaFilterLayout.addWidget(self.SweepPulseDeltaFilterCount, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaFilterLayout, 7, 1, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.FilterLabel_4 = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.FilterLabel_4.setFont(font)
        self.FilterLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel_4.setObjectName("FilterLabel_4")
        self.verticalLayout_4.addWidget(self.FilterLabel_4)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 5, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.SweepPulseDeltaParameterFrame)
        self.widget.setObjectName("widget")
        self.gridLayout_9.addWidget(self.widget, 4, 1, 1, 1)
        self.SweepPulseDeltaCycleLayout = QtWidgets.QGridLayout()
        self.SweepPulseDeltaCycleLayout.setObjectName("SweepPulseDeltaCycleLayout")
        self.SweepPulseDeltaCycleList = QtWidgets.QPushButton(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaCycleList.setObjectName("SweepPulseDeltaCycleList")
        self.SweepPulseDeltaCycleLayout.addWidget(self.SweepPulseDeltaCycleList, 1, 1, 1, 1)
        self.SweepPulseDeltaCycleLabel = QtWidgets.QLabel(self.SweepPulseDeltaParameterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SweepPulseDeltaCycleLabel.setFont(font)
        self.SweepPulseDeltaCycleLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SweepPulseDeltaCycleLabel.setObjectName("SweepPulseDeltaCycleLabel")
        self.SweepPulseDeltaCycleLayout.addWidget(self.SweepPulseDeltaCycleLabel, 0, 0, 1, 2)
        self.SweepPulseDeltaCycle = QtWidgets.QSpinBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaCycle.setMinimum(5)
        self.SweepPulseDeltaCycle.setMaximum(60)
        self.SweepPulseDeltaCycle.setProperty("value", 5)
        self.SweepPulseDeltaCycle.setObjectName("SweepPulseDeltaCycle")
        self.SweepPulseDeltaCycleLayout.addWidget(self.SweepPulseDeltaCycle, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.SweepPulseDeltaCycleLayout, 4, 0, 1, 1)
        self.SweepPulseDeltaLowMeasure = QtWidgets.QCheckBox(self.SweepPulseDeltaParameterFrame)
        self.SweepPulseDeltaLowMeasure.setChecked(True)
        self.SweepPulseDeltaLowMeasure.setObjectName("SweepPulseDeltaLowMeasure")
        self.gridLayout_9.addWidget(self.SweepPulseDeltaLowMeasure, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.SweepPulseDeltaParameterFrame, 0, 0, 1, 1)
        self.TabWidget.addTab(self.SweepPulseDeltaTab, "")
        self.gridLayout.addWidget(self.TabWidget, 3, 1, 1, 1)
        self.BelowGraphsWidget = QtWidgets.QWidget(self.CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BelowGraphsWidget.sizePolicy().hasHeightForWidth())
        self.BelowGraphsWidget.setSizePolicy(sizePolicy)
        self.BelowGraphsWidget.setObjectName("BelowGraphsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BelowGraphsWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ClearButton = QtWidgets.QPushButton(self.BelowGraphsWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout.addWidget(self.ClearButton)
        self.RunningButton = QtWidgets.QRadioButton(self.BelowGraphsWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RunningButton.setFont(font)
        self.RunningButton.setDisabled(True)
        self.RunningButton.setObjectName("RunningButton")
        self.horizontalLayout.addWidget(self.RunningButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.ExitButton = QtWidgets.QPushButton(self.BelowGraphsWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout.addWidget(self.ExitButton)
        self.gridLayout.addWidget(self.BelowGraphsWidget, 4, 0, 1, 2)
        self.GraphFrame = QtWidgets.QFrame(self.CentralWidget)
        self.GraphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GraphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GraphFrame.setObjectName("GraphFrame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.GraphFrame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.PlotWidget = GraphicsLayoutWidget(self.GraphFrame)
        self.PlotWidget.setObjectName("PlotWidget")
        self.gridLayout_12.addWidget(self.PlotWidget, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.GraphFrame, 3, 0, 1, 1)
        self.TopWidget = QtWidgets.QWidget(self.CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopWidget.sizePolicy().hasHeightForWidth())
        self.TopWidget.setSizePolicy(sizePolicy)
        self.TopWidget.setObjectName("TopWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.TopWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.SourceRangeGridLayout = QtWidgets.QGridLayout()
        self.SourceRangeGridLayout.setObjectName("SourceRangeGridLayout")
        self.SourceRangeType = QtWidgets.QComboBox(self.TopWidget)
        self.SourceRangeType.setObjectName("SourceRangeType")
        self.SourceRangeType.addItem("")
        self.SourceRangeType.addItem("")
        self.SourceRangeGridLayout.addWidget(self.SourceRangeType, 1, 0, 1, 1)
        self.SourceRangeLabel = QtWidgets.QLabel(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SourceRangeLabel.setFont(font)
        self.SourceRangeLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.SourceRangeLabel.setObjectName("SourceRangeLabel")
        self.SourceRangeGridLayout.addWidget(self.SourceRangeLabel, 0, 0, 1, 2)
        self.SourceRangeValue = QtWidgets.QComboBox(self.TopWidget)
        self.SourceRangeValue.setObjectName("SourceRangeValue")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeValue.addItem("")
        self.SourceRangeGridLayout.addWidget(self.SourceRangeValue, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.SourceRangeGridLayout, 1, 3, 1, 2)
        self.StopButton = QtWidgets.QPushButton(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.gridLayout_7.addWidget(self.StopButton, 0, 3, 1, 3)
        self.StartButton = QtWidgets.QPushButton(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout_7.addWidget(self.StartButton, 0, 0, 1, 3)
        self.FilePathLabel = QtWidgets.QLabel(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FilePathLabel.setFont(font)
        self.FilePathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FilePathLabel.setObjectName("FilePathLabel")
        self.gridLayout_7.addWidget(self.FilePathLabel, 5, 0, 1, 1)
        self.UnitsLayout = QtWidgets.QVBoxLayout()
        self.UnitsLayout.setObjectName("UnitsLayout")
        self.Units = QtWidgets.QLabel(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Units.setFont(font)
        self.Units.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.Units.setObjectName("Units")
        self.UnitsLayout.addWidget(self.Units)
        self.UnitsComboBox = QtWidgets.QComboBox(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.UnitsComboBox.setFont(font)
        self.UnitsComboBox.setObjectName("UnitsComboBox")
        self.UnitsComboBox.addItem("")
        self.UnitsComboBox.addItem("")
        self.UnitsComboBox.addItem("")
        self.UnitsComboBox.addItem("")
        self.UnitsComboBox.addItem("")
        self.UnitsLayout.addWidget(self.UnitsComboBox)
        self.gridLayout_7.addLayout(self.UnitsLayout, 1, 2, 1, 1)
        self.VoltmeterRangeLayout = QtWidgets.QGridLayout()
        self.VoltmeterRangeLayout.setObjectName("VoltmeterRangeLayout")
        self.VoltmeterRangeValue = QtWidgets.QComboBox(self.TopWidget)
        self.VoltmeterRangeValue.setObjectName("VoltmeterRangeValue")
        self.VoltmeterRangeValue.addItem("")
        self.VoltmeterRangeValue.addItem("")
        self.VoltmeterRangeValue.addItem("")
        self.VoltmeterRangeValue.addItem("")
        self.VoltmeterRangeValue.addItem("")
        self.VoltmeterRangeLayout.addWidget(self.VoltmeterRangeValue, 1, 1, 1, 1)
        self.VoltmeterRangeLabel = QtWidgets.QLabel(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VoltmeterRangeLabel.setFont(font)
        self.VoltmeterRangeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VoltmeterRangeLabel.setObjectName("VoltmeterRangeLabel")
        self.VoltmeterRangeLayout.addWidget(self.VoltmeterRangeLabel, 0, 0, 1, 2)
        self.gridLayout_7.addLayout(self.VoltmeterRangeLayout, 2, 3, 1, 2)
        self.GPIBVerticalLayout = QtWidgets.QVBoxLayout()
        self.GPIBVerticalLayout.setObjectName("GPIBVerticalLayout")
        self.GPIBLabel = QtWidgets.QLabel(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GPIBLabel.setFont(font)
        self.GPIBLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPIBLabel.setObjectName("GPIBLabel")
        self.GPIBVerticalLayout.addWidget(self.GPIBLabel)
        self.GPIB = QtWidgets.QSpinBox(self.TopWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GPIB.sizePolicy().hasHeightForWidth())
        self.GPIB.setSizePolicy(sizePolicy)
        self.GPIB.setProperty("value", 12)
        self.GPIB.setObjectName("GPIB")
        self.GPIBVerticalLayout.addWidget(self.GPIB)
        self.gridLayout_7.addLayout(self.GPIBVerticalLayout, 1, 0, 1, 1)
        self.ComplianceAbortGridLayout = QtWidgets.QGridLayout()
        self.ComplianceAbortGridLayout.setObjectName("ComplianceAbortGridLayout")
        self.ComplianceAbortCheckBox = QtWidgets.QCheckBox(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComplianceAbortCheckBox.setFont(font)
        self.ComplianceAbortCheckBox.setObjectName("ComplianceAbortCheckBox")
        self.ComplianceAbortGridLayout.addWidget(self.ComplianceAbortCheckBox, 0, 0, 1, 1)
        self.ComplianceVoltage = QtWidgets.QDoubleSpinBox(self.TopWidget)
        self.ComplianceVoltage.setMinimum(0.1)
        self.ComplianceVoltage.setMaximum(105.0)
        self.ComplianceVoltage.setSingleStep(0.01)
        self.ComplianceVoltage.setProperty("value", 10.0)
        self.ComplianceVoltage.setObjectName("ComplianceVoltage")
        self.ComplianceAbortGridLayout.addWidget(self.ComplianceVoltage, 1, 1, 1, 1)
        self.ComplianceVoltageLabel = QtWidgets.QLabel(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComplianceVoltageLabel.setFont(font)
        self.ComplianceVoltageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ComplianceVoltageLabel.setObjectName("ComplianceVoltageLabel")
        self.ComplianceAbortGridLayout.addWidget(self.ComplianceVoltageLabel, 1, 0, 1, 1)
        self.ComplianceVoltageList = QtWidgets.QPushButton(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComplianceVoltageList.setFont(font)
        self.ComplianceVoltageList.setObjectName("ComplianceVoltageList")
        self.ComplianceAbortGridLayout.addWidget(self.ComplianceVoltageList, 2, 0, 1, 2)
        self.gridLayout_7.addLayout(self.ComplianceAbortGridLayout, 1, 5, 3, 1)
        self.CalibrateButton = QtWidgets.QPushButton(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CalibrateButton.setFont(font)
        self.CalibrateButton.setObjectName("CalibrateButton")
        self.gridLayout_7.addWidget(self.CalibrateButton, 5, 5, 1, 1)
        self.FilePath = QtWidgets.QLineEdit(self.TopWidget)
        self.FilePath.setObjectName("FilePath")
        self.gridLayout_7.addWidget(self.FilePath, 5, 2, 1, 1)
        self.SaveNewButton = QtWidgets.QPushButton(self.TopWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SaveNewButton.setFont(font)
        self.SaveNewButton.setObjectName("SaveNewButton")
        self.gridLayout_7.addWidget(self.SaveNewButton, 5, 3, 1, 1)
        self.gridLayout.addWidget(self.TopWidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.CentralWidget)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dIdVDeltaLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Differential current (dI) for the sweep. Alternately added and subtracted from each step of the sweep. </p></body></html>"))
        self.dIdVDeltaLabel.setText(_translate("MainWindow", "Delta (uA)"))
        self.dIdVDeltaCurr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Differential current (dI) for the sweep. Alternately added and subtracted from each step of the sweep. </p></body></html>"))
        self.dIdVDelayLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Delay used to allow current to settle when output changes to next stepped delta level. Occurs after a trigger from 2182A.</p></body></html>"))
        self.dIdVDelayLabel.setText(_translate("MainWindow", "Delay (ms)"))
        self.dIdVDelay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Delay used to allow current to settle when output changes to next stepped delta level. Occurs after a trigger from 2182A.</p></body></html>"))
        self.dIdVStepSizeLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Size increment for each step of the sweep (without delta applied). If step size larger than start-stop interval, will readjust to provide a 100-point differential conductance sweep.</p></body></html>"))
        self.dIdVStepSizeLabel.setText(_translate("MainWindow", "Step Size (uA)"))
        self.dIdVStepSize.setToolTip(_translate("MainWindow", "<html><head/><body><p>Size increment for each step of the sweep (without delta applied). If step size larger than start-stop interval, will readjust to provide a 100-point differential conductance sweep.</p></body></html>"))
        self.dIdVFilterWindowLabel.setText(_translate("MainWindow", "Window (% Range)"))
        self.dIdVFilterCountLabel.setText(_translate("MainWindow", "Filter Count"))
        self.dIdVFilterCheckbox.setText(_translate("MainWindow", "Filter On"))
        self.dIdVFilterLabel.setText(_translate("MainWindow", "Repeating Filter"))
        self.FilterLabel.setText(_translate("MainWindow", "Filtering"))
        self.dIdVRateLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Integration time for the voltage measurement. Noise-optimized between 1-5 PLC. 1 PLC is 16.67ms for a 60Hz line.</p></body></html>"))
        self.dIdVRateLabel.setText(_translate("MainWindow", "Meas. Rate (PLC)"))
        self.dIdVRate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Integration time for the voltage measurement. Noise-optimized between 1-5 PLC. 1 PLC is 16.67ms for a 60Hz line.</p></body></html>"))
        self.dIdVStopCurrLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Current that is the middle step of the last cycle (not the highest current sourced).</p></body></html>"))
        self.dIdVStopCurrLabel.setText(_translate("MainWindow", "End Current (uA)"))
        self.dIdVStopCurr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Current that is the middle step of the last cycle (not the highest current sourced).</p></body></html>"))
        self.dIdVStartCurrLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start current for the sweep. Middle of first delta interval (not the lowest current sourced).</p></body></html>"))
        self.dIdVStartCurrLabel.setText(_translate("MainWindow", "Start Current (uA)"))
        self.dIdVStartCurr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start current for the sweep. Middle of first delta interval (not the lowest current sourced).</p></body></html>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.dIdVTab), _translate("MainWindow", "Differential Conductance"))
        self.DeltaHighCurrLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DeltaHighCurrLabel.setText(_translate("MainWindow", "High Current (uA)"))
        self.DeltaHighCurr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DeltaDelayLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time to wait before taking measurements after changing current--&lt;15ms may be inexact</p></body></html>"))
        self.DeltaDelayLabel.setText(_translate("MainWindow", "Delay (ms)"))
        self.DeltaDelay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time to wait before taking measurements after changing current before doing anything else--&lt;15ms may be inexact.</p></body></html>"))
        self.DeltaPulseCountLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DeltaPulseCountLabel.setText(_translate("MainWindow", "Pulse Count"))
        self.DeltaPulseCount.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DeltaLowCurrLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DeltaLowCurrLabel.setText(_translate("MainWindow", "Low Current (uA)"))
        self.DeltaLowCurr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DeltaFilterWindowLabel.setText(_translate("MainWindow", "Window (% Range)"))
        self.DeltaFilterCheckbox.setText(_translate("MainWindow", "Filter On"))
        self.DeltaFilterCountLabel.setText(_translate("MainWindow", "Filter Count"))
        self.DeltaFilterComboBox.setItemText(0, _translate("MainWindow", "Moving"))
        self.DeltaFilterComboBox.setItemText(1, _translate("MainWindow", "Repeating"))
        self.DeltaRateLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Integration time for the voltage measurement. Noise-optimized between 1-5 PLC. 1 PLC is 16.67ms for a 60Hz line.</p></body></html>"))
        self.DeltaRateLabel.setText(_translate("MainWindow", "Meas. Rate (PLC)"))
        self.DeltaRate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Integration time for the voltage measurement. Noise-optimized between 1-5 PLC. 1 PLC is 16.67ms for a 60Hz line.</p></body></html>"))
        self.FilterLabel_2.setText(_translate("MainWindow", "Filtering"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.DeltaTab), _translate("MainWindow", "Delta"))
        self.FixedPulseDeltaLowILabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.FixedPulseDeltaLowILabel.setText(_translate("MainWindow", "Low Current (uA)"))
        self.FixedPulseDeltaLowI.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.FixedPulseDeltaDelayLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time to allow pulse to settle before triggering 2182A to perform a measurement. Should be &lt; pulse width.</p></body></html>"))
        self.FixedPulseDeltaDelayLabel.setText(_translate("MainWindow", "Delay (us)"))
        self.FixedPulseDeltaDelay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time to allow pulse to settle before triggering 2182A to perform a measurement. Should be &lt; pulse width.</p></body></html>"))
        self.FixedPulseDeltaCycleLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Period of one pulse delta cycle (trigger LOW measurement on line cycle, trigger HIGH on line cycle, remain HIGH for pulse width, trigger LOW measurement on next line cycle, wait for completion of interval)</p></body></html>"))
        self.FixedPulseDeltaCycleLabel.setText(_translate("MainWindow", "Cycle Interval (PLC)"))
        self.FixedPulseDeltaCycle.setToolTip(_translate("MainWindow", "<html><head/><body><p>Period of one pulse delta cycle (trigger LOW measurement on line cycle, trigger HIGH on line cycle, remain HIGH for pulse width, trigger LOW measurement on next line cycle, wait for completion of interval)</p></body></html>"))
        self.FixedPulseDeltaWidthLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Duration of each HIGH and LOW pulse</p></body></html>"))
        self.FixedPulseDeltaWidthLabel.setText(_translate("MainWindow", "Pulse Width (us)"))
        self.FixedPulseDeltaWidth.setToolTip(_translate("MainWindow", "<html><head/><body><p>Duration of each HIGH and LOW pulse</p></body></html>"))
        self.FixedPulseDeltaHighILabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.FixedPulseDeltaHighILabel.setText(_translate("MainWindow", "High Current (uA)"))
        self.FixedPulseDeltaHighI.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of measurements to take at each current reading (IV sweeps)</p></body></html>"))
        self.DutyCycleLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Percentage of time the pulse is HIGH during a single pulse delta cycle.</p></body></html>"))
        self.DutyCycleLabel.setText(_translate("MainWindow", "Duty Cycle (%)"))
        self.DutyCycle.setToolTip(_translate("MainWindow", "<html><head/><body><p>Percentage of time the pulse is HIGH during a single pulse delta cycle.</p></body></html>"))
        self.FixedPulseDeltaCountLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of pulses to emit for the measurement. </p></body></html>"))
        self.FixedPulseDeltaCountLabel.setText(_translate("MainWindow", "Pulse Count"))
        self.FixedPulseDeltaCount.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of pulses to emit for the measurement</p></body></html>"))
        self.FixedPulseDeltaFilterWindowLabel.setText(_translate("MainWindow", "Window (% Range)"))
        self.FixedPulseDeltaFilterCountLabel.setText(_translate("MainWindow", "Filter Count"))
        self.FixedPulseDeltaFilterCheckbox.setText(_translate("MainWindow", "Filter On"))
        self.FixedPulseDeltaComboBox.setItemText(0, _translate("MainWindow", "Moving"))
        self.FixedPulseDeltaComboBox.setItemText(1, _translate("MainWindow", "Repeating"))
        self.FixedPulseDeltaLowMeasure.setToolTip(_translate("MainWindow", "<html><head/><body><p>Perform the second LOW measurement (after the HIGH) pulse. Do not use if thermal effects are expected to be large.</p></body></html>"))
        self.FixedPulseDeltaLowMeasure.setText(_translate("MainWindow", "Low Measure?"))
        self.FilterLabel_3.setText(_translate("MainWindow", "Filtering"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.FixedPulseDeltaTab), _translate("MainWindow", "Fixed Pulse Delta"))
        self.SweepTypeComboBox.setItemText(0, _translate("MainWindow", "Staircase"))
        self.SweepTypeComboBox.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.SweepTypeComboBox.setItemText(2, _translate("MainWindow", "Custom"))
        self.SweepPulseDeltaStartI.setToolTip(_translate("MainWindow", "<html><head/><body><p>Height of initial pulse in the sweep.</p></body></html>"))
        self.SweepPulseDeltaIList.setToolTip(_translate("MainWindow", "<html><head/><body><p>Provide a list of source currents for a manual sweep only (opens a dialog box).</p></body></html>"))
        self.SweepPulseDeltaIList.setText(_translate("MainWindow", "List"))
        self.SweepPulseDeltaStartILabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Height of initial pulse in the sweep.</p></body></html>"))
        self.SweepPulseDeltaStartILabel.setText(_translate("MainWindow", "Start Current (uA)"))
        self.SweepPulseDeltaEndILabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Final pulse height in the sweep.</p></body></html>"))
        self.SweepPulseDeltaEndILabel.setText(_translate("MainWindow", "End Current (uA)"))
        self.SweepPulseDeltaEndI.setToolTip(_translate("MainWindow", "<html><head/><body><p>Final pulse height in the sweep.</p></body></html>"))
        self.SweepPulseDeltaIStepLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pulse step height for the sweep (configurable for staircase sweep only)</p></body></html>"))
        self.SweepPulseDeltaIStepLabel.setText(_translate("MainWindow", "I Step (uA)"))
        self.SweepPulseDeltaIStep.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pulse step height for the sweep (configurable for staircase sweep only)</p></body></html>"))
        self.SweepPulseDeltaPointsLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of steps in the sweep (configurable in logarithmic and custom sweeps).</p></body></html>"))
        self.SweepPulseDeltaPointsLabel.setText(_translate("MainWindow", "Number Points"))
        self.SweepPulseDeltaPoints.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of steps in the sweep (configurable in logarithmic and custom sweeps).</p></body></html>"))
        self.SweepPulseDeltaSweepsLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of sweeps to perform during the measurement</p></body></html>"))
        self.SweepPulseDeltaSweepsLabel.setText(_translate("MainWindow", "Number Sweeps"))
        self.SweepPulseDeltaSweeps.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of sweeps to perform during the measurement</p></body></html>"))
        self.SweepPulseDeltaWidthLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Duration of each HIGH and LOW pulse</p></body></html>"))
        self.SweepPulseDeltaWidthLabel.setText(_translate("MainWindow", "Pulse Width (us)"))
        self.SweepPulseDeltaWidth.setToolTip(_translate("MainWindow", "<html><head/><body><p>Duration of each HIGH and LOW pulse</p></body></html>"))
        self.SweepPulseDeltaFilterLabel.setText(_translate("MainWindow", "Moving Filter"))
        self.SweepPulseDeltaFilterWindowLabel.setText(_translate("MainWindow", "Window (% Range)"))
        self.SweepPulseDeltaFilterCountLabel.setText(_translate("MainWindow", "Filter Count"))
        self.SweepPulseDeltaFilterCheckbox.setText(_translate("MainWindow", "Filter On"))
        self.FilterLabel_4.setText(_translate("MainWindow", "Filtering"))
        self.SweepPulseDeltaCycleList.setToolTip(_translate("MainWindow", "<html><head/><body><p>Provide a list of cycle intervals for a custom sweep only (opens a dialog box).</p></body></html>"))
        self.SweepPulseDeltaCycleList.setText(_translate("MainWindow", "List"))
        self.SweepPulseDeltaCycleLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Period of one pulse delta cycle (trigger LOW measurement on line cycle, trigger HIGH on line cycle, remain HIGH for pulse width, trigger LOW measurement on next line cycle, wait for completion of interval). Use &quot;List&quot; for custom sweeps.</p></body></html>"))
        self.SweepPulseDeltaCycleLabel.setText(_translate("MainWindow", "Cycle Interval (PLC)"))
        self.SweepPulseDeltaCycle.setToolTip(_translate("MainWindow", "<html><head/><body><p>Period of one pulse delta cycle (trigger LOW measurement on line cycle, trigger HIGH on line cycle, remain HIGH for pulse width, trigger LOW measurement on next line cycle, wait for completion of interval). Use &quot;List&quot; for custom sweeps.</p></body></html>"))
        self.SweepPulseDeltaLowMeasure.setText(_translate("MainWindow", "Low Measure?"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.SweepPulseDeltaTab), _translate("MainWindow", "Sweep Pulse Delta"))
        self.ClearButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Clear graphs without deleting data.</p></body></html>"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.RunningButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>If selected, measurement is occurring.</p></body></html>"))
        self.RunningButton.setText(_translate("MainWindow", "Running?"))
        self.ExitButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Safely aborts measurement (if necessary), turns off output, and exits the program.</p></body></html>"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))
        self.SourceRangeType.setToolTip(_translate("MainWindow", "<html><head/><body><p>Range for the 6221 Current Source. &quot;Best&quot; will choose the lowest range that encompasses the measurement points, &quot;Auto&quot; will auto-update the range at each measurement point (with current dropping to 0 during the switch), and &quot;Manual&quot; allows the user to choose a fixed source range. </p></body></html>"))
        self.SourceRangeType.setItemText(0, _translate("MainWindow", "Best"))
        self.SourceRangeType.setItemText(1, _translate("MainWindow", "Fixed"))
        self.SourceRangeLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Range for the 6221 Current Source. &quot;Best&quot; will choose the lowest range that encompasses the measurement points, &quot;Auto&quot; will auto-update the range at each measurement point (with current dropping to 0 during the switch), and &quot;Manual&quot; allows the user to choose a fixed source range. </p></body></html>"))
        self.SourceRangeLabel.setText(_translate("MainWindow", "Source Range"))
        self.SourceRangeValue.setToolTip(_translate("MainWindow", "<html><head/><body><p>For &quot;Manual&quot; ranging, set the source current range. Choose the lowest range that encompasses your measurement points.</p></body></html>"))
        self.SourceRangeValue.setItemText(0, _translate("MainWindow", "2nA"))
        self.SourceRangeValue.setItemText(1, _translate("MainWindow", "20nA"))
        self.SourceRangeValue.setItemText(2, _translate("MainWindow", "200nA"))
        self.SourceRangeValue.setItemText(3, _translate("MainWindow", "2uA"))
        self.SourceRangeValue.setItemText(4, _translate("MainWindow", "20uA"))
        self.SourceRangeValue.setItemText(5, _translate("MainWindow", "200uA"))
        self.SourceRangeValue.setItemText(6, _translate("MainWindow", "2mA"))
        self.SourceRangeValue.setItemText(7, _translate("MainWindow", "20mA"))
        self.SourceRangeValue.setItemText(8, _translate("MainWindow", "100mA"))
        self.StopButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Safely aborts current measurement, turns off output, and resets for new measurement.</p></body></html>"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.StartButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Begin selected measurement</p></body></html>"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.FilePathLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>File where data will be saved. Either specify an existing file in the text box (will overwrite) or use &quot;Save New&quot; to create a new file.</p></body></html>"))
        self.FilePathLabel.setText(_translate("MainWindow", "File Path"))
        self.Units.setToolTip(_translate("MainWindow", "<html><head/><body><p>Output units for the measurement.</p></body></html>"))
        self.Units.setText(_translate("MainWindow", "Units"))
        self.UnitsComboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Output units for the measurement.</p></body></html>"))
        self.UnitsComboBox.setItemText(0, _translate("MainWindow", "Voltage (V)"))
        self.UnitsComboBox.setItemText(1, _translate("MainWindow", "(Differential) Conductance (S)"))
        self.UnitsComboBox.setItemText(2, _translate("MainWindow", "(Differential) Resistance (Ohms)"))
        self.UnitsComboBox.setItemText(3, _translate("MainWindow", "Average Power (W)"))
        self.UnitsComboBox.setItemText(4, _translate("MainWindow", "Peak Power (W)"))
        self.VoltmeterRangeValue.setToolTip(_translate("MainWindow", "<html><head/><body><p>2182A voltage measurement range settings.</p></body></html>"))
        self.VoltmeterRangeValue.setItemText(0, _translate("MainWindow", "10mV"))
        self.VoltmeterRangeValue.setItemText(1, _translate("MainWindow", "100mV"))
        self.VoltmeterRangeValue.setItemText(2, _translate("MainWindow", "1V"))
        self.VoltmeterRangeValue.setItemText(3, _translate("MainWindow", "10V"))
        self.VoltmeterRangeValue.setItemText(4, _translate("MainWindow", "100V"))
        self.VoltmeterRangeValue.setCurrentIndex(2)
        self.VoltmeterRangeLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Range setting for the 2182A voltmeter. &quot;Auto&quot; will update the range automatically based on the measurements, and &quot;Manual&quot; will allow you to specify a range setting. If &quot;Manual,&quot; choose the lowest range setting that will accommodate your expected voltages.</p></body></html>"))
        self.VoltmeterRangeLabel.setText(_translate("MainWindow", "Voltmeter Range"))
        self.GPIBLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>GPIB address for the Keithley 6221 Current Source.</p></body></html>"))
        self.GPIBLabel.setText(_translate("MainWindow", "GPIB Address"))
        self.GPIB.setToolTip(_translate("MainWindow", "<html><head/><body><p>GPIB address for the Keithley 6221 Current Source.</p></body></html>"))
        self.ComplianceAbortCheckBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>If true, measurement operation will abort if the current source goes into compliance. Disabled by default.</p></body></html>"))
        self.ComplianceAbortCheckBox.setText(_translate("MainWindow", "Compliance Abort?"))
        self.ComplianceVoltage.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maximum voltage output for the 6221 Current Source. Suggested to make compliance voltage at least 2V above expected output voltage to avoid overshoot.</p></body></html>"))
        self.ComplianceVoltageLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maximum voltage output for the 6221 Current Source. Suggested to make compliance voltage at least 2V above expected output voltage to avoid overshoot.</p></body></html>"))
        self.ComplianceVoltageLabel.setText(_translate("MainWindow", "Compliance (V)"))
        self.ComplianceVoltageList.setToolTip(_translate("MainWindow", "<html><head/><body><p>Provide a list of compliance voltages for a manual sweep (opens a dialog box).</p></body></html>"))
        self.ComplianceVoltageList.setText(_translate("MainWindow", "List"))
        self.CalibrateButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Initiates a Low-Level (10mV only) ACAL procedure for the 2182A. Must be performed whenever the internal temperature and TCAL vary by &gt;1C. Takes about 5 minutes and does not require disconnecting anything (unlike the full ACAL, which calibrates the 10mV and 100V ranges).</p></body></html>"))
        self.CalibrateButton.setText(_translate("MainWindow", "Calibrate 2182A"))
        self.FilePath.setToolTip(_translate("MainWindow", "<html><head/><body><p>Path to file where data will be saved. Either specify an existing file (will overwrite) or use &quot;Save New&quot; to create a new file.</p></body></html>"))
        self.SaveNewButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save a new file for the measurement (opens a dialog box)</p></body></html>"))
        self.SaveNewButton.setText(_translate("MainWindow", "Save New"))

from pyqtgraph import GraphicsLayoutWidget

#if __name__ == "__main__":
#    import sys
#    app = QtWidgets.QApplication(sys.argv)
#    MainWindow = QtWidgets.QMainWindow()
#    ui = Ui_MainWindow()
#    ui.setupUi(MainWindow)
#    MainWindow.show()
#    sys.exit(app.exec_())
#
